/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://s2rf4ly67vgrjjbpotgefwkrki.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y57jeyw7evb2zckzxoz77bb2z4",
    "aws_cognito_identity_pool_id": "us-east-1:aefcf624-b0ae-44a9-a78e-38063509ae8b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1OrM9Qbwo",
    "aws_user_pools_web_client_id": "5m627c2qac2n674h9mpuhdujtq",
    "oauth": {
        "domain": "fortknox7dc461c3-7dc461c3-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.undefeatedsoftware.com/federated/fortknox/signinRedirect/",
        "redirectSignOut": "https://www.undefeatedsoftware.com/federated/fortknox/signoutRedirect/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
